spring:
    application:
        name: be-voluongquang
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/voluongquang}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:123456}
        # url: jdbc:postgresql://ep-purple-rice-a1c7ac6x.ap-southeast-1.aws.neon.tech/voluongquang?sslmode=require&channel_binding=require
        # username: neondb_owner
        # password: npg_obe3TBOj1CKH
    # driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        # show-sql: true

    liquibase:
        change-log: classpath:db/changelog/master-changelog.xml
        enabled: true
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
